---
collections:
  - name: https://github.com/ansible-collections/community.kubernetes
    type: git
    version: 0.11.1
  - name: https://github.com/ansible-collections/community.general
    type: git
    version: 4.8.0
